SSH接続についての説明の追加
KeioAIConsortium/docs pull request #9
Opened 2020-06-17 12:28 UTC by 190ikp

# WHAT

以下の2項目の説明を追加

1. SSHでの接続方法
2. jupyterhub-singleuser-instanceへのSSH

# WHY

1については問い合わせが多かったため
2については今後需要がありそうなので追加

2020-06-17 12:36 UTC, 190ikp commented
Jupyter Notebookって一部書いている箇所があったので，JupyterHubインスタンスって書いた方が良さそう (？)

2020-06-17 12:37 UTC, mt-caret requested changes

2020-06-17 12:37 UTC, mt-caret commented on jupyterhub_user_manual.md
> +また、Jupyter Notebookインスタンスに直接SSH接続をしたい場合は、公開鍵認証を使用することでアクセスできるようになります。これにはJupyterHubでTerminalを開き、ご自身の端末のSSH公開鍵を`~/.ssh/autorized_keys`に書き込んでおく必要があります。\
Jupyter Notebookへの公開鍵認証を用いたSSHの記述、別な節に分けた方いいんじゃないかな

2020-06-17 12:37 UTC, mt-caret commented on jupyterhub_user_manual.md
> +でサーバにSSH接続します。`-A`はagent forwardingを行うオプションです。\
これssh-agentが動いてないとうまくいかなくない？あとgateway -> jupyterhub-singleuser-instanceを公開鍵認証でやるならgatewayの`~/.ssh/authorized_keys`にも公開鍵おいておけばgatewayログインもパスワードいらなくなって便利そうだし、それも書いてもいいかも

2020-06-17 12:37 UTC, mt-caret commented on jupyterhub_user_manual.md
> +apt list --installed | grep cuda-repo
:innocent:

2020-06-17 12:37 UTC, mt-caret commented on jupyterhub_user_manual.md
> +sudo apt install --yes cuda-toolkit-11-0
autoremoveを最後に持っていったのはcuda-toolkit-10-1とcuda-toolkit-11-0の間に共通の依存関係があったら消した後入れ直してちょっと無駄かもな、って思ったからなんだけどどうだろう

2020-06-17 14:07 UTC, 190ikp commented on jupyterhub_user_manual.md
> +また、Jupyter Notebookインスタンスに直接SSH接続をしたい場合は、公開鍵認証を使用することでアクセスできるようになります。これにはJupyterHubでTerminalを開き、ご自身の端末のSSH公開鍵を`~/.ssh/autorized_keys`に書き込んでおく必要があります。\
それは迷ったんですが，文脈的に似た内容 (JupyterHubにアクセスすることなくリソースを使用する) だと思ってとりあえずまとめました．
分けます．

2020-06-17 14:07 UTC, 190ikp commented on jupyterhub_user_manual.md
> +でサーバにSSH接続します。`-A`はagent forwardingを行うオプションです。\
ssh-agentについてはLinuxとOS Xはそうですね，書いておいたほうがいいかもしれません．
Windowsについては[こちら](https://docs.microsoft.com/ja-jp/windows-server/administration/openssh/openssh_keymanagement)に載っていますが，やはり書いたほうが良いでしょうか...？

2020-06-17 14:10 UTC, 190ikp commented on jupyterhub_user_manual.md
> +sudo apt install --yes cuda-toolkit-11-0
依存関係を一度完全にpurgeしてからのほうが確実だと思います．
ちなみに， nvidiaのドキュメントだとcuda関連のパッケージを手で全部消すようになっていますね (さすがにここまでしなくていいとは思いますが)
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#removing-cuda-tk-and-driver

2020-06-17 14:46 UTC, 190ikp commented
なんか書いてたらボリュームそこそこあるし，もはや別ページに分けたほうが良い気がしてきた...

2020-06-17 19:08 UTC, 190ikp commented on jupyterhub_user_manual.md
> +でサーバにSSH接続します。`-A`はagent forwardingを行うオプションです。\
載せました

2020-06-18 01:15 UTC, mt-caret commented
そろそろページ分けた方いい分かるなあ
でもこれどういう風にやるのが正しいのか分からん
一部をよくある質問ページみたいなのに移す、みたいな？

2020-06-18 01:25 UTC, mt-caret requested changes

2020-06-18 01:25 UTC, mt-caret commented on jupyterhub_user_manual.md
> +- Mac OS X / Linuxの場合: ターミナル上でOpenSSHが使用できます。
今はmacOSだしmacOS (OS X）とかが正しいのかなあ

2020-06-18 01:25 UTC, mt-caret commented on jupyterhub_user_manual.md
>  再び同じ場所にSSHアクセスを行い、これで正常にログインができれば設定は完了です。接続を切り、ブラウザで [https://cocoa.ai.hc.keio.ac.jp](https://cocoa.ai.hc.keio.ac.jp) にアクセスしてください。ここで、`https`ではなく`http`と打ってしまうと正しくアクセスできないので注意してください。出てきたログインフォームにてユーザ名
httpと打つとうまく繋がらない問題頭悪いしはやくどうにかしたいよな

そういえばこれエラーが出たら何度か再読込してくれみたいな指示入れたほうがいいな

2020-06-18 01:25 UTC, mt-caret commented on jupyterhub_user_manual.md
> +  - 各ゲートウェイサーバ間でホームディレクトリは同期しませんのでご注意ください
ここの表現、形を合わせるなら
- JupyterHubインスタンスへのSSH公開鍵の登録
...
- ゲートウェイサーバへのSSH公開鍵の登録
の方が良さそう

optional、書いたほうがいいと思うけど日本語で同じことを伝える上手い表現欲しいな

2020-06-18 03:18 UTC, 190ikp commented on jupyterhub_user_manual.md
> +- Mac OS X / Linuxの場合: ターミナル上でOpenSSHが使用できます。
ほんと…ほんともう

2020-06-18 03:26 UTC, 190ikp commented on jupyterhub_user_manual.md
> +  - 各ゲートウェイサーバ間でホームディレクトリは同期しませんのでご注意ください
任意、とでも書いときますか

2020-06-18 03:47 UTC, mt-caret approved these changes

2020-06-18 03:49 UTC, merged